INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('AFG', 'AF', 'Afghanistan', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('ALB', 'AL', 'Albania', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('DZA', 'DZ', 'Algeria', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('ASM', 'AS', 'American Samoa', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('AND', 'AD', 'Andorra', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('AGO', 'AO', 'Angola', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('AIA', 'AI', 'Anguilla', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('ATG', 'AG', 'Antigua and Barbuda', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('ARG', 'AR', 'Argentina', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('ARM', 'AM', 'Armenia', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('ABW', 'AW', 'Aruba', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('AUS', 'AU', 'Australia', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('AUT', 'AT', 'Austria', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('AZE', 'AZ', 'Azerbaijan', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('BHS', 'BS', 'Bahamas', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('BHR', 'BH', 'Bahrain', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('BGD', 'BD', 'Bangladesh', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('BRB', 'BB', 'Barbados', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('BLR', 'BY', 'Belarus', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('BEL', 'BE', 'Belgium', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('BLZ', 'BZ', 'Belize', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('BEN', 'BJ', 'Benin', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('BMU', 'BM', 'Bermuda', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('BTN', 'BT', 'Bhutan', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('BOL', 'BO', 'Bolivia, Plurinational State of', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('BIH', 'BA', 'Bosnia and Herzegovina', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('BWA', 'BW', 'Botswana', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('BRA', 'BR', 'Brazil', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('IOT', 'IO', 'British Indian Ocean Territory', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('BGR', 'BG', 'Bulgaria', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('BFA', 'BF', 'Burkina Faso', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('BDI', 'BI', 'Burundi', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('KHM', 'KH', 'Cambodia', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('CMR', 'CM', 'Cameroon', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('CAN', 'CA', 'Canada', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('CPV', 'CV', 'Cape Verde', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('CYM', 'KY', 'Cayman Islands', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('CAF', 'CF', 'Central African Republic', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('TCD', 'TD', 'Chad', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('CHL', 'CL', 'Chile', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('CHN', 'CN', 'China', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('COL', 'CO', 'Colombia', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('COM', 'KM', 'Comoros', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('COG', 'CG', 'Congo', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('COD', 'CD', 'Democratic Republic of the Congo', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('COK', 'CK', 'Cook Islands', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('CRI', 'CR', 'Costa Rica', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('CIV', 'CI', 'Côte d''Ivoire', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('HRV', 'HR', 'Croatia', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('CUB', 'CU', 'Cuba', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('CUW', 'CW', 'Curaçao', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('CYP', 'CY', 'Cyprus', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('CZE', 'CZ', 'Czech Republic', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('DNK', 'DK', 'Denmark', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('DJI', 'DJ', 'Djibouti', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('DMA', 'DM', 'Dominica', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('DOM', 'DO', 'Dominican Republic', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('ECU', 'EC', 'Ecuador', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('EGY', 'EG', 'Egypt', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('SLV', 'SV', 'El Salvador', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('GNQ', 'GQ', 'Equatorial Guinea', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('ERI', 'ER', 'Eritrea', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('EST', 'EE', 'Estonia', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('ETH', 'ET', 'Ethiopia', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('FIN', 'FI', 'Finland', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('FRA', 'FR', 'France', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('PYF', 'PF', 'French Polynesia', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('GAB', 'GA', 'Gabon', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('GMB', 'GM', 'Gambia', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('GEO', 'GE', 'Georgia', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('DEU', 'DE', 'Germany', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('GHA', 'GH', 'Ghana', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('GIB', 'GI', 'Gibraltar', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('GRC', 'GR', 'Greece', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('GRL', 'GL', 'Greenland', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('GRD', 'GD', 'Grenada', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('GUM', 'GU', 'Guam', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('GTM', 'GT', 'Guatemala', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('GGY', 'GG', 'Guernsey', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('GIN', 'GN', 'Guinea', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('GNB', 'GW', 'Guinea-Bissau', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('HTI', 'HT', 'Haiti', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('HND', 'HN', 'Honduras', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('HKG', 'HK', 'Hong Kong', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('HUN', 'HU', 'Hungary', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('ISL', 'IS', 'Iceland', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('IND', 'IN', 'India', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('IDN', 'ID', 'Indonesia', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('IRN', 'IR', 'Iran, Islamic Republic of', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('IRQ', 'IQ', 'Iraq', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('IRL', 'IE', 'Ireland', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('IMN', 'IM', 'Isle of Man', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('ISR', 'IL', 'Israel', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('ITA', 'IT', 'Italy', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('JAM', 'JM', 'Jamaica', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('JPN', 'JP', 'Japan', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('JEY', 'JE', 'Jersey', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('JOR', 'JO', 'Jordan', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('KAZ', 'KZ', 'Kazakhstan', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('KEN', 'KE', 'Kenya', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('KIR', 'KI', 'Kiribati', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('PRK', 'KP', 'North Korea', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('KOR', 'KR', 'South Korea', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('KWT', 'KW', 'Kuwait', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('KGZ', 'KG', 'Kyrgyzstan', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('LAO', 'LA', 'Lao People''s Democratic Republic', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('LVA', 'LV', 'Latvia', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('LBN', 'LB', 'Lebanon', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('LSO', 'LS', 'Lesotho', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('LBR', 'LR', 'Liberia', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('LBY', 'LY', 'Libya', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('LIE', 'LI', 'Liechtenstein', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('LTU', 'LT', 'Lithuania', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('LUX', 'LU', 'Luxembourg', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('MAC', 'MO', 'Macao', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('MKD', 'MK', 'Republic of Macedonia', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('MDG', 'MG', 'Madagascar', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('MWI', 'MW', 'Malawi', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('MYS', 'MY', 'Malaysia', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('MDV', 'MV', 'Maldives', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('MLI', 'ML', 'Mali', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('MLT', 'MT', 'Malta', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('MHL', 'MH', 'Marshall Islands', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('MTQ', 'MQ', 'Martinique', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('MRT', 'MR', 'Mauritania', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('MUS', 'MU', 'Mauritius', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('MEX', 'MX', 'Mexico', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('FSM', 'FM', 'Micronesia, Federated States of', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('MDA', 'MD', 'Republic of Moldova', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('MCO', 'MC', 'Monaco', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('MNG', 'MN', 'Mongolia', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('MNE', 'ME', 'Montenegro', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('MSR', 'MS', 'Montserrat', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('MAR', 'MA', 'Morocco', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('MOZ', 'MZ', 'Mozambique', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('MMR', 'MM', 'Myanmar', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('NAM', 'NA', 'Namibia', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('NRU', 'NR', 'Nauru', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('NPL', 'NP', 'Nepal', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('NLD', 'NL', 'Netherlands', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('NZL', 'NZ', 'New Zealand', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('NIC', 'NI', 'Nicaragua', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('NER', 'NE', 'Niger', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('NGA', 'NG', 'Nigeria', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('NIU', 'NU', 'Niue', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('NFK', 'NF', 'Norfolk Island', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('MNP', 'MP', 'Northern Mariana Islands', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('NOR', 'NO', 'Norway', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('OMN', 'OM', 'Oman', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('PAK', 'PK', 'Pakistan', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('PLW', 'PW', 'Palau', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('PSE', 'PS', 'Palestinian Territory', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('PAN', 'PA', 'Panama', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('PNG', 'PG', 'Papua New Guinea', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('PRY', 'PY', 'Paraguay', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('PER', 'PE', 'Peru', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('PHL', 'PH', 'Philippines', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('PCN', 'PN', 'Pitcairn', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('POL', 'PL', 'Poland', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('PRT', 'PT', 'Portugal', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('PRI', 'PR', 'Puerto Rico', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('QAT', 'QA', 'Qatar', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('ROU', 'RO', 'Romania', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('RUS', 'RU', 'Russia', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('RWA', 'RW', 'Rwanda', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('KNA', 'KN', 'Saint Kitts and Nevis', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('LCA', 'LC', 'Saint Lucia', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('VCT', 'VC', 'Saint Vincent and the Grenadines', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('WSM', 'WS', 'Samoa', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('SMR', 'SM', 'San Marino', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('STP', 'ST', 'Sao Tome and Principe', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('SAU', 'SA', 'Saudi Arabia', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('SEN', 'SN', 'Senegal', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('SRB', 'RS', 'Serbia', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('SYC', 'SC', 'Seychelles', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('SLE', 'SL', 'Sierra Leone', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('SGP', 'SG', 'Singapore', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('SXM', 'SX', 'Sint Maarten', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('SVK', 'SK', 'Slovakia', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('SVN', 'SI', 'Slovenia', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('SLB', 'SB', 'Solomon Islands', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('SOM', 'SO', 'Somalia', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('ZAF', 'ZA', 'South Africa', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('SSD', 'SS', 'South Sudan', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('ESP', 'ES', 'Spain', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('LKA', 'LK', 'Sri Lanka', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('SDN', 'SD', 'Sudan', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('SUR', 'SR', 'Suriname', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('SWZ', 'SZ', 'Eswatini', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('SWE', 'SE', 'Sweden', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('CHE', 'CH', 'Switzerland', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('SYR', 'SY', 'Syria', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('TWN', 'TW', 'Taiwan', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('TJK', 'TJ', 'Tajikistan', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('TZA', 'TZ', 'Tanzania', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('THA', 'TH', 'Thailand', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('TLS', 'TL', 'Timor-Leste', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('TGO', 'TG', 'Togo', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('TKL', 'TK', 'Tokelau', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('TON', 'TO', 'Tonga', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('TTO', 'TT', 'Trinidad and Tobago', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('TUN', 'TN', 'Tunisia', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('TUR', 'TR', 'Turkey', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('TKM', 'TM', 'Turkmenistan', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('TCA', 'TC', 'Turks and Caicos Islands', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('TUV', 'TV', 'Tuvalu', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('UGA', 'UG', 'Uganda', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('UKR', 'UA', 'Ukraine', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('ARE', 'AE', 'United Arab Emirates', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('GBR', 'GB', 'United Kingdom', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('USA', 'US', 'United States', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('URY', 'UY', 'Uruguay', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('UZB', 'UZ', 'Uzbekistan', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('VUT', 'VU', 'Vanuatu', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('VEN', 'VE', 'Venezuela', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('VNM', 'VN', 'Vietnam', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('VIR', 'VI', 'Virgin Islands', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('YEM', 'YE', 'Yemen', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('ZMB', 'ZM', 'Zambia', false);
INSERT INTO public."Countries" ("Code3", "Code2", "Name", "Visited") VALUES ('ZWE', 'ZW', 'Zimbabwe', false);
